name: takeout_lib
description: TakeoutFM Library
version: 0.25.2 # #version#
publish_to: 'none'
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.18
  audio_session: ^0.2.2
  cached_network_image: ^3.4.1
  chewie: ^1.13.0
  connectivity_plus: ^7.0.0
  crypto: ^3.0.7
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  flutter_cache_manager: ^3.4.1
  hive_ce: ^2.16.0
  http: ^1.6.0
  hydrated_bloc: ^10.1.1
  logger: ^2.6.2
  json_annotation: ^4.9.0
  just_audio: ^0.10.5
  nested: ^1.0.0
  octo_image: ^2.1.0
  palette_generator: ^0.3.3+7
  path: ^1.9.1
  path_provider: ^2.1.5
  receive_intent: ^0.2.7
  rxdart: ^0.28.0
  video_player: ^2.10.1
  listenbrainz_dart: ^0.0.4
  storage_space_fork: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  flutter_lints: ^6.0.0
  test: ^1.26.3
  hive_ce_generator: ^1.10.0

# need this since 7.4.0 is broken
# https://github.com/google/json_serializable.dart/issues/1485
#dependenc y_overrides:
#  analyzer: 7.3.0

flutter:
  uses-material-design: true
  generate: true
