name: takeout_mobile
description: TakeoutFM
publish_to: 'none'
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  takeout_lib: ^0.25.2
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.8.1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  logger: ^2.6.2
  nested: ^1.0.0
  recase: ^4.1.0
  receive_intent: ^0.2.7
  rxdart: ^0.28.0
  timeago: ^3.7.1
  timeago_flutter: ^3.7.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  audio_service: ^0.18.18
  swipeable_tile: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
